/**
 * @fileoverview Database seed – 100 eco tasks + badge definitions
 * Run with: npm run seed (from /server directory)
 */
require('dotenv').config()
const mongoose = require('mongoose')
const Task     = require('../models/Task')
const { Badge } = require('../models/Badge')
const connectDB = require('./db')

const TASKS = [
  { dayNumber:1,  title:'Skip the Plastic Bag',           category:'waste',  difficulty:'Easy',   estimatedMinutes:2,  waterSaved:0,   co2Reduced:30,  plasticAvoided:8,   basePoints:10, description:'Refuse a plastic bag at the store today. Bring your own reusable bag or carry items by hand if possible. Every plastic bag takes 1,000 years to decompose.',                   ecoFactTip:'Over 1 trillion plastic bags are used globally each year. Saying no to just one saves 8g of plastic from reaching landfills.' },
  { dayNumber:2,  title:'5-Minute Shorter Shower',         category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:50,  co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Cut your shower time by 5 minutes. Set a timer or play a song that\'s under 5 minutes and try to finish before it ends.',                                                  ecoFactTip:'A standard shower uses 10 liters per minute. Cutting 5 minutes saves 50 liters — enough for an average person\'s daily drinking water for a month.' },
  { dayNumber:3,  title:'Unplug Standby Devices',          category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:80,  plasticAvoided:0,   basePoints:10, description:'Walk through your home and unplug devices not in use — chargers, TVs on standby, and appliances. Phantom power accounts for up to 10% of household electricity.',        ecoFactTip:'Standby electronics in the US alone waste $19 billion worth of electricity each year, emitting 44 million tonnes of CO₂.' },
  { dayNumber:4,  title:'Meatless Monday Meal',            category:'nature', difficulty:'Easy',   estimatedMinutes:30, waterSaved:2400,co2Reduced:3000,plasticAvoided:0,   basePoints:10, description:'Cook or order one completely plant-based meal today. Explore a new vegetarian or vegan recipe for breakfast, lunch, or dinner.',                                            ecoFactTip:'Producing one beef burger requires 2,400 liters of water and generates over 3kg of CO₂. One plant-based meal makes a massive difference.' },
  { dayNumber:5,  title:'Carry a Reusable Water Bottle',   category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:50,  plasticAvoided:15,  basePoints:10, description:'Use a reusable water bottle all day instead of buying single-use plastic bottles. Refill it at least 3 times throughout the day.',                                          ecoFactTip:'Americans use 50 billion plastic water bottles a year. Only 23% are recycled. One reusable bottle prevents over 150 disposable bottles annually.' },
  { dayNumber:6,  title:'Line-Dry Your Laundry',           category:'energy', difficulty:'Easy',   estimatedMinutes:10, waterSaved:0,   co2Reduced:1800,plasticAvoided:0,   basePoints:10, description:'Air-dry your laundry today instead of using the dryer. Hang clothes outside or on an indoor rack.',                                                                        ecoFactTip:'Clothes dryers use more electricity than any other household appliance. Line drying one load saves up to 1.8kg of CO₂ and extends your clothes\' life.' },
  { dayNumber:7,  title:'Plant Something Green',            category:'nature', difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:200, plasticAvoided:0,   basePoints:15, description:'Plant a seed, a herb, or a small plant today. Even a single pot of basil on your windowsill counts! Plants purify air and boost mental health.',                          ecoFactTip:'A single tree can absorb up to 22kg of CO₂ per year and produce enough oxygen for 4 people. Starting small still matters.' },
  { dayNumber:8,  title:'Walk or Cycle Instead of Drive',  category:'energy', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:2100,plasticAvoided:0,   basePoints:15, description:'Replace one car trip today with walking or cycling. Even a 2km walk instead of driving prevents significant CO₂ emissions.',                                                 ecoFactTip:'The average car emits about 120g of CO₂ per kilometer. Replacing just one short drive per week saves over 60kg of CO₂ per year.' },
  { dayNumber:9,  title:'Fix a Dripping Tap',              category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:150, co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Check all taps and showers in your home for leaks and fix any drips. A dripping tap can waste thousands of liters per year. Tighten the washer or call a plumber.',      ecoFactTip:'A tap dripping once per second wastes over 11,000 liters of water per year — enough to fill 50 bathtubs.' },
  { dayNumber:10, title:'Switch to Reusable Coffee Cup',   category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:60,  plasticAvoided:22,  basePoints:10, description:'If you buy coffee, bring your own reusable cup. Most cafés offer a discount for this. If you make coffee at home, great — you\'re already ahead!',                       ecoFactTip:'Over 16 billion disposable coffee cups are used annually worldwide. Most are unrecyclable due to their plastic lining.' },
  { dayNumber:11, title:'Eat Seasonal & Local Produce',    category:'nature', difficulty:'Easy',   estimatedMinutes:20, waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:10, description:'Choose fruits and vegetables that are in season locally. Visit a farmer\'s market or check labels for local produce. Seasonal food travels fewer miles to reach you.',    ecoFactTip:'Food transportation accounts for 6% of all food-related emissions. Buying local reduces your food\'s carbon footprint by up to 50%.' },
  { dayNumber:12, title:'Take a Cold Shower',              category:'energy', difficulty:'Hard',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:400, plasticAvoided:0,   basePoints:20, description:'Take a fully cold shower today! Cold showers use zero heating energy. They also improve circulation and boost alertness.',                                                  ecoFactTip:'Heating water accounts for 15–20% of a home\'s total energy use. A cold shower eliminates that entirely and can also improve your immune system.' },
  { dayNumber:13, title:'Start a Compost Bin',             category:'waste',  difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:300, plasticAvoided:0,   basePoints:15, description:'Set up a small compost bin in your kitchen or backyard for food scraps: vegetable peels, coffee grounds, eggshells. Compost returns nutrients to the earth.',             ecoFactTip:'Food waste in landfills produces methane, a greenhouse gas 25x more potent than CO₂. Composting reduces this and creates rich garden fertilizer.' },
  { dayNumber:14, title:'Digital Detox Evening',           category:'energy', difficulty:'Medium', estimatedMinutes:120,waterSaved:0,   co2Reduced:150, plasticAvoided:0,   basePoints:15, description:'Spend the evening without any screens — no phone, TV, or computer. Read a book, take a walk, or play a board game. Reduce phantom energy and mental load.',              ecoFactTip:'The internet produces over 900 million tonnes of CO₂ per year. Reducing screen time for even one evening saves energy at data centers worldwide.' },
  { dayNumber:15, title:'Refuse a Straw',                  category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:10,  plasticAvoided:5,   basePoints:10, description:'When ordering drinks today, say "no straw please." Alternatively, switch to a reusable metal, bamboo, or silicone straw permanently.',                                     ecoFactTip:'Over 8 billion straws pollute the world\'s beaches. They\'re one of the top 10 items found in ocean cleanups and are eaten by sea turtles and fish.' },
  { dayNumber:16, title:'Buy Second-Hand',                  category:'waste',  difficulty:'Medium', estimatedMinutes:60, waterSaved:0,   co2Reduced:800, plasticAvoided:30,  basePoints:15, description:'Purchase at least one item second-hand today — clothing, books, electronics, or furniture. Check charity shops, thrift stores, or online resale platforms.',               ecoFactTip:'The fashion industry produces 10% of global CO₂ emissions. A single used T-shirt purchase saves 2.5kg of CO₂ versus buying new.' },
  { dayNumber:17, title:'Turn Off Lights When Leaving',    category:'energy', difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:120, plasticAvoided:0,   basePoints:10, description:'Make a conscious habit today: every time you leave a room, switch off the light. Put a sticky note on doors as a reminder if needed.',                                    ecoFactTip:'Lighting accounts for 15% of global electricity consumption. Switching off unused lights consistently reduces a home\'s energy use by up to 10%.' },
  { dayNumber:18, title:'Cook a Zero-Waste Meal',           category:'waste',  difficulty:'Hard',   estimatedMinutes:45, waterSaved:0,   co2Reduced:400, plasticAvoided:50,  basePoints:20, description:'Plan and cook a meal that uses up leftovers, has no packaging waste, and produces no food scraps (or composted ones). Challenge yourself creatively!',                    ecoFactTip:'One-third of all food produced globally — 1.3 billion tonnes — is wasted each year. Zero-waste cooking directly combats this crisis.' },
  { dayNumber:19, title:'Clean Up Your Local Area',         category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:200, basePoints:15, description:'Take a bag outside and pick up litter from your neighborhood, park, or beach for 30 minutes. Every piece of plastic you remove protects local wildlife.',                 ecoFactTip:'8 million metric tonnes of plastic enter our oceans every year. A 30-minute local cleanup can collect up to 5kg of waste before it reaches waterways.' },
  { dayNumber:20, title:'Switch to Eco Search Engine',      category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:50,  plasticAvoided:0,   basePoints:10, description:'Change your default browser to an eco-friendly search engine like Ecosia, which plants trees with its ad revenue. It works just as well as Google!',                     ecoFactTip:'Ecosia has planted over 200 million trees worldwide. Each search you make contributes directly to reforestation in areas most affected by deforestation.' },
  { dayNumber:21, title:'Wash Clothes in Cold Water',       category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:10, description:'Do a laundry load using cold water instead of warm or hot. Modern detergents are formulated to work just as effectively in cold water.',                                   ecoFactTip:'90% of a washing machine\'s energy goes to heating water. Cold washing saves up to 0.5kg of CO₂ per load and preserves your clothes\' colors and fabric.' },
  { dayNumber:22, title:'Eat Vegan for a Full Day',         category:'nature', difficulty:'Hard',   estimatedMinutes:60, waterSaved:4000,co2Reduced:6000,plasticAvoided:0,   basePoints:20, description:'Challenge yourself to eat fully vegan for the entire day. Plan breakfast, lunch, dinner, and snacks in advance. Explore plant-based alternatives.',                      ecoFactTip:'A vegan diet reduces food-related CO₂ emissions by 73% and water use by 55%. One full vegan day saves an average of 4,000 liters of water.' },
  { dayNumber:23, title:'Donate Unused Items',              category:'waste',  difficulty:'Medium', estimatedMinutes:40, waterSaved:0,   co2Reduced:600, plasticAvoided:0,   basePoints:15, description:'Gather clothing, books, or household items you no longer use and arrange to donate them to a charity, shelter, or community center.',                                     ecoFactTip:'Every tonne of donated textiles saves 3.6 tonnes of CO₂ compared to new production. Items in good condition should never go to landfill.' },
  { dayNumber:24, title:'Use Public Transport',             category:'energy', difficulty:'Medium', estimatedMinutes:40, waterSaved:0,   co2Reduced:2500,plasticAvoided:0,   basePoints:15, description:'Use bus, metro, tram, or train for at least one journey today. If you\'re already car-free, great — share this tip with someone who isn\'t.',                            ecoFactTip:'A bus carries up to 50 people using roughly the same fuel as 10 cars. Choosing transit over a solo car trip cuts your per-journey CO₂ by up to 80%.' },
  { dayNumber:25, title:'Reduce Food Packaging',            category:'waste',  difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:200, plasticAvoided:80,  basePoints:15, description:'Actively choose products with minimal or zero packaging at the grocery store today. Buy loose fruit and veg, use paper bags, and opt for glass over plastic.',           ecoFactTip:'Packaging accounts for over 40% of plastic produced globally. Choosing unwrapped or minimally packaged products directly reduces demand for virgin plastic.' },
  { dayNumber:26, title:'Learn About a Local Eco Issue',    category:'nature', difficulty:'Easy',   estimatedMinutes:20, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Spend 20 minutes researching a local environmental issue — deforestation, river pollution, air quality, or urban heat. Share what you learn with one person.',           ecoFactTip:'Environmental literacy is one of the strongest predictors of pro-environmental behavior. Informed citizens drive policy change and community action.' },
  { dayNumber:27, title:'Install a Low-Flow Shower Head',  category:'water',  difficulty:'Hard',   estimatedMinutes:30, waterSaved:300, co2Reduced:100, plasticAvoided:0,   basePoints:20, description:'Research and purchase a low-flow or water-saving shower head. Installation is typically 10 minutes with a wrench. This is a long-term impact investment.',               ecoFactTip:'Low-flow shower heads use 6–8 liters per minute vs. 15–20L for standard ones. A family of four saves over 160,000 liters of water per year.' },
  { dayNumber:28, title:'Host a Green Conversation',        category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Talk to a friend, colleague, or family member about your 30-day eco challenge. Share what you\'ve learned and inspire them to try even one eco habit.',                ecoFactTip:'Social influence is one of the most powerful drivers of behavior change. Research shows that people are 65% more likely to adopt new habits when others they know have too.' },
  { dayNumber:29, title:'Audit Your Home Energy Use',       category:'energy', difficulty:'Hard',   estimatedMinutes:45, waterSaved:0,   co2Reduced:1000,plasticAvoided:0,   basePoints:20, description:'Conduct a home energy audit: check insulation, draft-proofing, appliance efficiency ratings, and thermostat settings. Identify 3 ways to reduce your energy use long-term.', ecoFactTip:'Home energy audits reduce energy bills by an average of 25%. Proper insulation alone can cut heating costs by 40% and prevent tons of CO₂ annually.' },
  { dayNumber:30, title:'Commit to One Eco Habit Forever',  category:'nature', difficulty:'Medium', estimatedMinutes:10, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'You\'ve made it to Day 30! Reflect on your 30-day journey. Choose one eco habit from the challenge that you will commit to permanently. Write it down and share it.', ecoFactTip:'The science of habit formation shows that 30 days of consistent behavior creates a neural pathway that makes the habit automatic. You\'ve already done the hard part!' },
  // --- Days 31-100 ---

  // WATER (17 Tasks)
  { dayNumber:31, title:'Turn Off Tap While Brushing',     category:'water',  difficulty:'Easy',   estimatedMinutes:2,  waterSaved:15,  co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Turn the water off while you brush your teeth morning and night. Only turn it on to wet the brush and rinse.', ecoFactTip:'Leaving the water running while brushing your teeth can waste up to 15 liters of water every single time you brush.' },
  { dayNumber:32, title:'Catch Shower Warm-Up Water',      category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:10,  co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Place a bucket in the shower to catch the clean water that flows while waiting for it to heat up. Use it to water plants.', ecoFactTip:'Catching warm-up water can save 10 to 15 liters per shower, preserving clean drinking water for better uses.' },
  { dayNumber:33, title:'Wash Car with a Bucket',          category:'water',  difficulty:'Medium', estimatedMinutes:45, waterSaved:300, co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'If washing your car, use a bucket and sponge instead of a continuous running hose.', ecoFactTip:'Washing a car with a hose uses over 350 liters of water. Using a bucket reduces that to about 30 liters.' },
  { dayNumber:34, title:'Run Dishwasher Only When Full',   category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:30,  co2Reduced:50,  plasticAvoided:0,   basePoints:10, description:'Wait until the dishwasher is completely full before running it to maximize water efficiency per dish.', ecoFactTip:'A modern dishwasher is highly water-efficient, but running it half-empty entirely negates those environmental benefits.' },
  { dayNumber:35, title:'Eco-Friendly Laundry Detergent',  category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:20,  plasticAvoided:40,  basePoints:15, description:'Switch to detergent strips or powder in a cardboard box to prevent toxic runoff and plastic jug waste.', ecoFactTip:'Standard laundry detergents contain synthetic chemicals that harm aquatic life when they drain into local waterways.' },
  { dayNumber:36, title:'Turn Off Tap Washing Dishes',     category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:40,  co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Turn off the tap while scrubbing dishes. Only turn the water back on to rinse, or use a filled basin.', ecoFactTip:'A running kitchen tap wastes roughly 6-10 liters of water per minute. Scrubbing with the tap off saves massive amounts.' },
  { dayNumber:37, title:'Install Toilet Tank Bank',        category:'water',  difficulty:'Hard',   estimatedMinutes:15, waterSaved:150, co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Place a plastic bottle filled with pebbles/water into your older toilet\'s tank to displace water and save liters per flush.', ecoFactTip:'Water displacement tricks can save up to 2 liters per flush, saving thousands of liters a year for older toilets.' },
  { dayNumber:38, title:'Sweep Instead of Hose',           category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:150, co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Use a broom to clean your driveway, patio, or sidewalk instead of spraying it down with a water hose.', ecoFactTip:'Using a hose to clean a driveway or patio wastes roughly 150 to 200 liters of treated municipal water in just 10 minutes.' },
  { dayNumber:39, title:'Check for Toilet Leaks',          category:'water',  difficulty:'Hard',   estimatedMinutes:10, waterSaved:100, co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Put a few drops of food coloring in your toilet tank. If color appears in the bowl without flushing, fix the leak.', ecoFactTip:'A silently leaking toilet flapper can invisibly waste over 100,000 liters of water in a single year.' },
  { dayNumber:40, title:'Reuse Cooking Water for Plants',  category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:5,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Let the water you used to boil pasta or vegetables cool down, then use it to water your indoor or outdoor plants.', ecoFactTip:'Starchy or nutrient-rich cooking water acts as a free, mild fertilizer for plants while recycling water.' },
  { dayNumber:41, title:'Shorten Washing Machine Cycle',   category:'water',  difficulty:'Medium', estimatedMinutes:5,  waterSaved:20,  co2Reduced:50,  plasticAvoided:0,   basePoints:15, description:'Select the "quick wash" or "eco" setting on your washing machine for lightly soiled clothes.', ecoFactTip:'Quick wash cycles use up to 30% less water and energy, and they also reduce the wear and tear on your clothing.' },
  { dayNumber:42, title:'Fix Outside Hoses/Sprinklers',    category:'water',  difficulty:'Hard',   estimatedMinutes:45, waterSaved:500, co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Inspect your outdoor garden hoses and sprinkler systems for leaks, and patch or replace the broken connections.', ecoFactTip:'An outdoor irrigation leak with a diameter of just 1/32nd of an inch can waste over 23,000 liters of water a month.' },
  { dayNumber:43, title:'Install a Faucet Aerator',        category:'water',  difficulty:'Hard',   estimatedMinutes:30, waterSaved:200, co2Reduced:50,  plasticAvoided:0,   basePoints:20, description:'Purchase and screw a low-flow aerator onto your kitchen or bathroom sink faucet to reduce water flow.', ecoFactTip:'Aerators mix air into the water stream, maintaining pressure while reducing water usage by up to 50%.' },
  { dayNumber:44, title:'Defrost Food in Fridge',          category:'water',  difficulty:'Medium', estimatedMinutes:5,  waterSaved:30,  co2Reduced:10,  plasticAvoided:0,   basePoints:15, description:'Plan ahead and thaw frozen food in the refrigerator overnight instead of running it under hot water.', ecoFactTip:'Thawing food under running tap water wastes gallons of water and the energy required to heat it.' },
  { dayNumber:45, title:'Water Plants at Dawn/Dusk',       category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:20,  co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Shift your plant watering schedule to the early morning or late evening when the sun is down.', ecoFactTip:'Watering during the heat of the day causes up to 30% of the water to evaporate before it can be absorbed by the roots.' },
  { dayNumber:46, title:'Only Run Full Loads of Laundry',  category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:40,  co2Reduced:100, plasticAvoided:0,   basePoints:10, description:'Hold off on doing laundry until you have a completely full basket to maximize the machine\'s water use.', ecoFactTip:'Washing two half-loads uses considerably more water and energy than washing one completely full load.' },
  { dayNumber:47, title:'Rainwater Harvesting Setup',      category:'water',  difficulty:'Hard',   estimatedMinutes:60, waterSaved:200, co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Set up a rain barrel or a simple bucket system under a gutter downspout to catch water for your garden.', ecoFactTip:'A typical roof can yield over 2,000 liters of water from just one inch of rainfall.' },

  // WASTE (17 Tasks)
  { dayNumber:48, title:'Zero Food Waste Day',             category:'waste',  difficulty:'Hard',   estimatedMinutes:30, waterSaved:0,   co2Reduced:250, plasticAvoided:0,   basePoints:20, description:'Commit to throwing away absolutely zero food today. Eat leftovers, compost peels, and only serve what you can finish.', ecoFactTip:'If global food waste were a country, it would be the third-largest emitter of greenhouse gases in the world.' },
  { dayNumber:49, title:'Switch to a Bamboo Toothbrush',   category:'waste',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:10,  plasticAvoided:15,  basePoints:10, description:'Order or buy a compostable bamboo toothbrush to replace your current plastic one when it wears out.', ecoFactTip:'Over 1 billion plastic toothbrushes are thrown away annually in the US alone, and they never fully break down.' },
  { dayNumber:50, title:'Upcycle an Old Item',             category:'waste',  difficulty:'Hard',   estimatedMinutes:60, waterSaved:0,   co2Reduced:100, plasticAvoided:50,  basePoints:20, description:'Take something broken or old (like a glass jar or torn shirt) and turn it into something useful again.', ecoFactTip:'Upcycling reduces the need for raw materials, lowering manufacturing emissions and diverting items from landfills.' },
  { dayNumber:51, title:'Buy in Bulk to Avoid Plastic',    category:'waste',  difficulty:'Medium', estimatedMinutes:45, waterSaved:0,   co2Reduced:50,  plasticAvoided:100, basePoints:15, description:'Buy grains, nuts, or pasta from bulk bins using your own containers, or buy the largest size available.', ecoFactTip:'Buying in bulk minimizes single-use plastic packaging and reduces the transport emissions of shipping lighter items.' },
  { dayNumber:52, title:'Use Reusable Silicone Bags',      category:'waste',  difficulty:'Medium', estimatedMinutes:5,  waterSaved:0,   co2Reduced:20,  plasticAvoided:10,  basePoints:15, description:'Swap out single-use plastic ziplock bags for reusable silicone bags or glass Tupperware for snacks and leftovers.', ecoFactTip:'The average family uses 500 plastic ziplock bags a year. A reusable silicone bag can replace thousands of disposables.' },
  { dayNumber:53, title:'Bring Own Takeout Containers',    category:'waste',  difficulty:'Hard',   estimatedMinutes:10, waterSaved:0,   co2Reduced:40,  plasticAvoided:60,  basePoints:20, description:'When going to pick up food, ask the restaurant to place your meal in the reusable containers you bring from home.', ecoFactTip:'Styrofoam and plastic takeout containers make up nearly half of all plastic waste found in ocean surface pollution.' },
  { dayNumber:54, title:'Mend a Piece of Clothing',        category:'waste',  difficulty:'Hard',   estimatedMinutes:45, waterSaved:2000,co2Reduced:150, plasticAvoided:0,   basePoints:20, description:'Sew a button, patch a hole, or fix a hem on a piece of clothing instead of throwing it away or replacing it.', ecoFactTip:'Extending the life of clothes by just 9 months reduces carbon, water, and waste footprints of the item by 20-30%.' },
  { dayNumber:55, title:'Switch to Bar Soap',              category:'waste',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:20,  plasticAvoided:30,  basePoints:10, description:'Replace liquid body wash or hand soap with a traditional bar of soap wrapped in paper or cardboard.', ecoFactTip:'Liquid soap has a 25% larger carbon footprint than bar soap, largely due to the weight of water and the plastic bottles.' },
  { dayNumber:56, title:'Make Veggie Broth from Scraps',   category:'waste',  difficulty:'Medium', estimatedMinutes:45, waterSaved:0,   co2Reduced:100, plasticAvoided:0,   basePoints:15, description:'Boil vegetable scraps (onion skins, carrot ends, celery tops) in water to make a zero-waste, delicious homemade broth.', ecoFactTip:'Reusing food scraps prevents them from emitting methane in a landfill and reduces the need to buy packaged broth.' },
  { dayNumber:57, title:'Use Cloth Napkins',               category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:10,  co2Reduced:20,  plasticAvoided:0,   basePoints:10, description:'Replace paper towels or paper napkins with reusable cloth napkins during all your meals today.', ecoFactTip:'If every household used just one less paper roll a year, it would save 54,000 trees from being cut down.' },
  { dayNumber:58, title:'Reuse Glass Jars for Storage',    category:'waste',  difficulty:'Easy',   estimatedMinutes:10, waterSaved:0,   co2Reduced:15,  plasticAvoided:20,  basePoints:10, description:'Clean out an empty pasta sauce or jam jar and use it to store bulk dry goods, leftovers, or small household items.', ecoFactTip:'Glass is 100% infinitely recyclable, but reusing it directly requires zero manufacturing energy compared to recycling it.' },
  { dayNumber:59, title:'Learn City Recycling Rules',      category:'waste',  difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:50,  plasticAvoided:0,   basePoints:15, description:'Look up your local municipality\'s exact recycling guidelines. Learn exactly what plastics and papers are accepted.', ecoFactTip:'Wish-cycling (putting incorrect items in the recycling bin) contaminates whole batches, causing them to be sent to landfills.' },
  { dayNumber:60, title:'No Paper Towels for a Day',       category:'waste',  difficulty:'Hard',   estimatedMinutes:5,  waterSaved:15,  co2Reduced:20,  plasticAvoided:0,   basePoints:20, description:'Hide your paper towels for 24 hours. Use microfiber cloths, rags, or sponges for all kitchen and bathroom cleanup.', ecoFactTip:'To make one ton of paper towels, 17 trees and 20,000 gallons of water are consumed.' },
  { dayNumber:61, title:'Create Eco-Friendly Gift Wrap',   category:'waste',  difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:20,  plasticAvoided:15,  basePoints:15, description:'Wrap your next gift using newspaper, old maps, fabric scraps (Furoshiki), or brown paper bags instead of glossy paper.', ecoFactTip:'Most glossy or glittery wrapping paper cannot be recycled. Millions of tons of gift wrap end up in landfills.' },
  { dayNumber:62, title:'Switch to Loose-Leaf Tea',        category:'waste',  difficulty:'Easy',   estimatedMinutes:10, waterSaved:0,   co2Reduced:5,   plasticAvoided:10,  basePoints:10, description:'Brew your tea using a metal strainer and loose tea leaves rather than pre-packaged tea bags.', ecoFactTip:'Many commercial tea bags contain microplastics in the seal to keep them from falling apart in hot water.' },
  { dayNumber:63, title:'Toothpaste Tablets',              category:'waste',  difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:10,  plasticAvoided:15,  basePoints:15, description:'Swap out your plastic toothpaste tube for zero-waste toothpaste tablets that come in a recyclable jar or box.', ecoFactTip:'Over 1 billion plastic toothpaste tubes are sent to landfills every year because their mixed materials make them unrecyclable.' },
  { dayNumber:64, title:'Switch to a Reusable Razor',      category:'waste',  difficulty:'Hard',   estimatedMinutes:15, waterSaved:0,   co2Reduced:30,  plasticAvoided:20,  basePoints:20, description:'Invest in a stainless steel safety razor instead of buying disposable plastic razors or plastic cartridge heads.', ecoFactTip:'Over 2 billion disposable plastic razors are thrown away annually. A metal safety razor can last a lifetime.' },

  // ENERGY (18 Tasks)
  { dayNumber:65, title:'Switch to LED Bulbs',             category:'energy', difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:300, plasticAvoided:0,   basePoints:15, description:'Replace at least 3 high-use incandescent or CFL bulbs in your home with energy-efficient LED bulbs.', ecoFactTip:'LED bulbs use 75% less energy and last 25 times longer than traditional incandescent lighting.' },
  { dayNumber:66, title:'Clean Out Your Email Inbox',      category:'energy', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:30,  plasticAvoided:0,   basePoints:15, description:'Delete old emails, clear your spam folder, and empty the trash. Storing digital data requires massive server farms.', ecoFactTip:'Data centers account for 1% of global electricity demand. Deleting 1,000 emails saves about 30g of CO₂ emissions.' },
  { dayNumber:67, title:'Defrost Your Freezer',            category:'energy', difficulty:'Hard',   estimatedMinutes:60, waterSaved:0,   co2Reduced:150, plasticAvoided:0,   basePoints:20, description:'Empty and defrost your freezer. Ice buildup makes the motor work harder, consuming significantly more electricity.', ecoFactTip:'A freezer with just a quarter-inch of ice buildup can use up to 10% more energy to maintain its temperature.' },
  { dayNumber:68, title:'Lower Thermostat by 1 Degree',    category:'energy', difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:300, plasticAvoided:0,   basePoints:10, description:'Turn your heating down by 1°C (or AC up by 1°C). Put on a sweater if you feel chilly instead of cranking the heat.', ecoFactTip:'Lowering your thermostat by just 1 degree Celsius can cut your heating bill by 10% and significantly lower emissions.' },
  { dayNumber:69, title:'Use Natural Light All Day',       category:'energy', difficulty:'Easy',   estimatedMinutes:0,  waterSaved:0,   co2Reduced:100, plasticAvoided:0,   basePoints:10, description:'Keep all artificial lights off until the sun goes down. Open blinds and curtains to maximize natural daylight.', ecoFactTip:'Using natural daylight improves your mood and productivity while saving energy that would otherwise power daytime lighting.' },
  { dayNumber:70, title:'Walk or Bike for an Errand',      category:'energy', difficulty:'Hard',   estimatedMinutes:40, waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:20, description:'Pick an errand within 3 miles of your home and complete it by walking or biking instead of driving.', ecoFactTip:'Short car trips under 3 miles account for a massive percentage of daily traffic and are the least fuel-efficient.' },
  { dayNumber:71, title:'Unsubscribe from Retail Emails',  category:'energy', difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:20,  plasticAvoided:0,   basePoints:15, description:'Unsubscribe from at least 10 promotional email lists to reduce server energy and stop impulse buying.', ecoFactTip:'A single promotional email sent to millions requires massive energy from servers. Unsubscribing stops this cycle.' },
  { dayNumber:72, title:'Turn Oven Off 5 Mins Early',      category:'energy', difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:30,  plasticAvoided:0,   basePoints:10, description:'If you are baking, turn the oven off 5 minutes before the timer ends. The residual heat will finish cooking the food.', ecoFactTip:'Ovens hold their temperature very well. Turning them off early saves electricity or gas without affecting the meal.' },
  { dayNumber:73, title:'Support a Local Business',        category:'energy', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:100, plasticAvoided:0,   basePoints:15, description:'Buy your groceries, coffee, or a necessary item from an independent local business rather than a multinational chain.', ecoFactTip:'Local businesses source their products closer to home, drastically cutting down on shipping and freight emissions.' },
  { dayNumber:74, title:'Check Tire Pressure',             category:'energy', difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:80,  plasticAvoided:0,   basePoints:15, description:'Check your car or bike tire pressure. Inflate them to the recommended PSI to ensure maximum fuel and energy efficiency.', ecoFactTip:'Under-inflated tires increase rolling resistance, reducing gas mileage by up to 3% and wearing out tires faster.' },
  { dayNumber:75, title:'Use Lids While Cooking',          category:'energy', difficulty:'Easy',   estimatedMinutes:2,  waterSaved:0,   co2Reduced:25,  plasticAvoided:0,   basePoints:10, description:'Put a lid on your pots and pans while boiling water or cooking. It traps heat and cooks food much faster.', ecoFactTip:'Using a lid can reduce energy usage by up to 30% per meal by significantly reducing cooking time.' },
  { dayNumber:76, title:'Optimize Fridge Temperature',     category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:60,  plasticAvoided:0,   basePoints:10, description:'Set your refrigerator to 3-4°C (37-39°F) and freezer to -18°C (0°F). These are the most energy-efficient safe zones.', ecoFactTip:'Setting a fridge even 1 degree colder than necessary can increase its energy consumption by 5%.' },
  { dayNumber:77, title:'Manage Your Curtains',            category:'energy', difficulty:'Easy',   estimatedMinutes:2,  waterSaved:0,   co2Reduced:40,  plasticAvoided:0,   basePoints:10, description:'Close curtains/blinds during hot summer days to keep heat out, and open them in winter to let warm sunlight in.', ecoFactTip:'Strategic use of window coverings can reduce heat gain in summer by up to 33% and reduce heat loss in winter by 10%.' },
  { dayNumber:78, title:'Air Dry Your Dishes',             category:'energy', difficulty:'Easy',   estimatedMinutes:2,  waterSaved:0,   co2Reduced:40,  plasticAvoided:0,   basePoints:10, description:'If using a dishwasher, turn off the heated dry setting. Open the door slightly after the cycle and let them air dry.', ecoFactTip:'The heated dry cycle on a dishwasher consumes up to 15% of the machine\'s total energy use.' },
  { dayNumber:79, title:'Turn Off AC When Leaving',        category:'energy', difficulty:'Medium', estimatedMinutes:1,  waterSaved:0,   co2Reduced:150, plasticAvoided:0,   basePoints:15, description:'Double-check that the air conditioning or heating is completely turned off or heavily dialed back before leaving.', ecoFactTip:'Heating and cooling an empty home is one of the most common and easily preventable sources of residential energy waste.' },
  { dayNumber:80, title:'Clean Fridge Coils',              category:'energy', difficulty:'Hard',   estimatedMinutes:30, waterSaved:0,   co2Reduced:80,  plasticAvoided:0,   basePoints:20, description:'Pull your refrigerator away from the wall and vacuum the dust off the condenser coils at the back or bottom.', ecoFactTip:'Dusty coils force the compressor to work up to 30% harder, wasting significant electricity and shortening its life.' },
  { dayNumber:81, title:'Only Boil Needed Water',          category:'energy', difficulty:'Easy',   estimatedMinutes:2,  waterSaved:2,   co2Reduced:15,  plasticAvoided:0,   basePoints:10, description:'When making tea or coffee, fill the kettle with exactly the amount of water you need in your mug, no more.', ecoFactTip:'Overfilling the kettle wastes energy. The energy wasted boiling excess water in the UK could power half their streetlights.' },
  { dayNumber:82, title:'Calculate Carbon Footprint',      category:'energy', difficulty:'Hard',   estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Use an online carbon footprint calculator to see exactly where your highest emissions come from, and set a reduction goal.', ecoFactTip:'Understanding your personal carbon footprint provides the baseline data necessary to make the most impactful lifestyle changes.' },

  // NATURE (18 Tasks)
  { dayNumber:83, title:'Opt Out of Junk Mail',            category:'nature', difficulty:'Medium', estimatedMinutes:20, waterSaved:100, co2Reduced:50,  plasticAvoided:0,   basePoints:15, description:'Take 20 minutes to register online to opt-out of unsolicited mail, catalogs, and credit card offers.', ecoFactTip:'Over 100 million trees are cut down each year just to produce junk mail, which also wastes billions of gallons of water.' },
  { dayNumber:84, title:'Make a DIY Natural Cleaner',      category:'nature', difficulty:'Medium', estimatedMinutes:15, waterSaved:0,   co2Reduced:20,  plasticAvoided:50,  basePoints:15, description:'Mix equal parts white vinegar and water with a squeeze of lemon to create a multi-purpose cleaner in a reused bottle.', ecoFactTip:'Commercial cleaners contain harsh chemicals that pollute waterways and require heavy plastic packaging for transport.' },
  { dayNumber:85, title:'Read an Eco Conservation Article',category:'nature', difficulty:'Easy',   estimatedMinutes:15, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Find and read a reputable article about ocean conservation, forest protection, or renewable energy.', ecoFactTip:'Staying informed helps you make better purchasing decisions and makes you a stronger advocate for environmental policies.' },
  { dayNumber:86, title:'Plant a Tree or Donate to Plant', category:'nature', difficulty:'Hard',   estimatedMinutes:30, waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:20, description:'Physically plant a tree sapling in a suitable location or donate to a trusted tree-planting charity.', ecoFactTip:'Trees are nature\'s carbon capture technology. A mature tree absorbs 22kg of carbon dioxide per year.' },
  { dayNumber:87, title:'Avoid Palm Oil Today',            category:'nature', difficulty:'Hard',   estimatedMinutes:30, waterSaved:0,   co2Reduced:150, plasticAvoided:0,   basePoints:20, description:'Check ingredient lists and strictly avoid anything containing palm oil (found in many snacks, peanut butters, and cosmetics).', ecoFactTip:'Irresponsible palm oil harvesting is a leading cause of deforestation, destroying habitats of endangered orangutans.' },
  { dayNumber:88, title:'Grow Green Onions from Roots',    category:'nature', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:10,  plasticAvoided:0,   basePoints:10, description:'Save the bottom white root of a green onion and place it in a small glass of water. Watch it regrow in a few days!', ecoFactTip:'Regrowing kitchen scraps reduces the agricultural energy, water, and transport emissions needed to produce new vegetables.' },
  { dayNumber:89, title:'Share an Eco-Documentary',        category:'nature', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Recommend a powerful nature or environmental documentary to a friend or post about it on your social media.', ecoFactTip:'Visual storytelling is highly effective at shifting public opinion and inspiring community-wide environmental action.' },
  { dayNumber:90, title:'Try Plant-Based Milk',            category:'nature', difficulty:'Medium', estimatedMinutes:10, waterSaved:150, co2Reduced:80,  plasticAvoided:0,   basePoints:15, description:'Swap dairy milk for oat, almond, soy, or pea milk in your coffee, cereal, or cooking today.', ecoFactTip:'Producing a glass of dairy milk results in almost three times more greenhouse gas emissions than any plant-based alternative.' },
  { dayNumber:91, title:'Watch a Nature Documentary',      category:'nature', difficulty:'Easy',   estimatedMinutes:60, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Sit down and watch a documentary like Our Planet, Planet Earth, or My Octopus Teacher to reconnect with nature.', ecoFactTip:'Cultivating awe and appreciation for the natural world is psychologically proven to increase environmentally protective behaviors.' },
  { dayNumber:92, title:'Buy Ugly Produce',                category:'nature', difficulty:'Medium', estimatedMinutes:20, waterSaved:200, co2Reduced:50,  plasticAvoided:0,   basePoints:15, description:'Intentionally buy misshapen, scarred, or "ugly" fruits and vegetables at the store that others might leave behind.', ecoFactTip:'Supermarkets reject up to 30% of crops strictly based on cosmetic standards. Buying them directly fights food waste.' },
  { dayNumber:93, title:'Borrow Instead of Buying',        category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:500, co2Reduced:150, plasticAvoided:50,  basePoints:15, description:'Need a tool, a book, or a special appliance? Ask a neighbor, friend, or use a community library instead of buying it new.', ecoFactTip:'The average power drill is used for only 13 minutes in its entire lifetime. Sharing heavily reduces manufacturing emissions.' },
  { dayNumber:94, title:'Boycott Fast Fashion',            category:'nature', difficulty:'Hard',   estimatedMinutes:0,  waterSaved:2500,co2Reduced:100, plasticAvoided:0,   basePoints:20, description:'Commit to buying zero new clothing items from fast fashion brands. Buy second-hand or sustainable from now on.', ecoFactTip:'It takes 2,700 liters of water to make one cotton shirt—enough for one person to drink for two and a half years.' },
  { dayNumber:95, title:'Identify 3 Local Native Plants',  category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Use a plant identification app or book to find and identify three plant species native to your specific region.', ecoFactTip:'Native plants require significantly less water and fertilizer than lawns, and they provide crucial habitats for local pollinators.' },
  { dayNumber:96, title:'Make a Bug Hotel',                category:'nature', difficulty:'Hard',   estimatedMinutes:60, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Bundle hollow bamboo stems, twigs, and pinecones in a wooden box to create a habitat for solitary bees and beneficial insects.', ecoFactTip:'Insect populations have plummeted by 40% in recent decades. Bug hotels provide safe nesting spots for vital garden pollinators.' },
  { dayNumber:97, title:'Pledge to Volunteer',             category:'nature', difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Research local environmental cleanup groups, community gardens, or wildlife rescues and sign up for one volunteer shift.', ecoFactTip:'Hands-on environmental volunteering builds community resilience and vastly multiplies the impact of individual eco-actions.' },
  { dayNumber:98, title:'Write to a Politician',           category:'nature', difficulty:'Hard',   estimatedMinutes:45, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:20, description:'Write an email or letter to your local representative urging them to support green infrastructure or renewable energy.', ecoFactTip:'Systemic change requires political action. Representatives gauge public interest based directly on the volume of messages they receive.' },
  { dayNumber:99, title:'Share Your 100-Day Journey',      category:'nature', difficulty:'Easy',   estimatedMinutes:20, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Write a post, make a video, or write a journal entry detailing the best habits you learned during this challenge.', ecoFactTip:'Documenting and sharing your journey normalizes eco-friendly behavior, inspiring your community to take their own first steps.' },
  { dayNumber:100,title:'Host an Eco-Dinner Party',        category:'nature', difficulty:'Hard',   estimatedMinutes:120,waterSaved:0,   co2Reduced:500, plasticAvoided:100, basePoints:20, description:'Celebrate Day 100! Host a zero-waste, fully plant-based dinner for friends to celebrate completing the challenge.', ecoFactTip:'You have reached the end of the 100 Days! Small individual actions, when multiplied by millions of people, can literally change the world.' }
]

const BADGES = [
  { badgeId:'first_leaf',     name:'First Leaf',     icon:'🌱', rarity:'common',    description:'Complete your very first eco task', condition:'Complete Day 1' },
  { badgeId:'green_week',     name:'Green Week',      icon:'🌿', rarity:'uncommon',  description:'Maintain a 7-day streak',          condition:'7-day streak' },
  { badgeId:'month_master',   name:'Month Master',    icon:'🗓️', rarity:'rare',      description:'Maintain a 30-day streak',         condition:'30-day streak' },
  { badgeId:'halfway_hero',   name:'Halfway Hero',    icon:'⚡', rarity:'epic',      description:'Reach a 50-day streak',            condition:'50-day streak' },
  { badgeId:'eco_warrior',    name:'Eco Warrior',     icon:'🏆', rarity:'legendary', description:'Complete all 100 days',            condition:'Complete 100 days' },
  { badgeId:'water_guardian', name:'Water Guardian',  icon:'💧', rarity:'rare',      description:'Save 100 liters of water',         condition:'100L water saved' },
  { badgeId:'carbon_crusher', name:'Carbon Crusher',  icon:'🌍', rarity:'rare',      description:'Reduce 500g of CO₂',              condition:'500g CO₂ reduced' },
  { badgeId:'waste_buster',   name:'Waste Buster',    icon:'♻️', rarity:'uncommon',  description:'Avoid 200g of plastic',           condition:'200g plastic avoided' },
  { badgeId:'early_bird',     name:'Early Bird',      icon:'🌅', rarity:'uncommon',  description:'Complete a task before 8am',      condition:'Before 8am' },
]

const seed = async () => {
  await connectDB()
  console.log('🌱 Starting seed...')

  // Clear existing
  await Task.deleteMany({})
  await Badge.deleteMany({})
  console.log('  ✓ Cleared existing tasks and badges')

  // Insert tasks
  await Task.insertMany(TASKS)
  console.log(`  ✓ Seeded ${TASKS.length} tasks`)

  // Insert badges
  await Badge.insertMany(BADGES)
  console.log(`  ✓ Seeded ${BADGES.length} badges`)

  console.log('✅ Seed complete!')
  process.exit(0)
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err)
  process.exit(1)
})
