/**
 * @fileoverview Database seed – 30 eco tasks + badge definitions
 * Run with: npm run seed (from /server directory)
 */
require('dotenv').config()
const mongoose = require('mongoose')
const Task     = require('../models/Task')
const { Badge } = require('../models/Badge')
const connectDB = require('./db')

const TASKS = [
  { dayNumber:1,  title:'Skip the Plastic Bag',           category:'waste',  difficulty:'Easy',   estimatedMinutes:2,  waterSaved:0,   co2Reduced:30,  plasticAvoided:8,   basePoints:10, description:'Refuse a plastic bag at the store today. Bring your own reusable bag or carry items by hand if possible. Every plastic bag takes 1,000 years to decompose.',                   ecoFactTip:'Over 1 trillion plastic bags are used globally each year. Saying no to just one saves 8g of plastic from reaching landfills.' },
  { dayNumber:2,  title:'5-Minute Shorter Shower',         category:'water',  difficulty:'Easy',   estimatedMinutes:5,  waterSaved:50,  co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Cut your shower time by 5 minutes. Set a timer or play a song that\'s under 5 minutes and try to finish before it ends.',                                                  ecoFactTip:'A standard shower uses 10 liters per minute. Cutting 5 minutes saves 50 liters — enough for an average person\'s daily drinking water for a month.' },
  { dayNumber:3,  title:'Unplug Standby Devices',          category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:80,  plasticAvoided:0,   basePoints:10, description:'Walk through your home and unplug devices not in use — chargers, TVs on standby, and appliances. Phantom power accounts for up to 10% of household electricity.',        ecoFactTip:'Standby electronics in the US alone waste $19 billion worth of electricity each year, emitting 44 million tonnes of CO₂.' },
  { dayNumber:4,  title:'Meatless Monday Meal',            category:'nature', difficulty:'Easy',   estimatedMinutes:30, waterSaved:2400,co2Reduced:3000,plasticAvoided:0,   basePoints:10, description:'Cook or order one completely plant-based meal today. Explore a new vegetarian or vegan recipe for breakfast, lunch, or dinner.',                                            ecoFactTip:'Producing one beef burger requires 2,400 liters of water and generates over 3kg of CO₂. One plant-based meal makes a massive difference.' },
  { dayNumber:5,  title:'Carry a Reusable Water Bottle',   category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:50,  plasticAvoided:15,  basePoints:10, description:'Use a reusable water bottle all day instead of buying single-use plastic bottles. Refill it at least 3 times throughout the day.',                                          ecoFactTip:'Americans use 50 billion plastic water bottles a year. Only 23% are recycled. One reusable bottle prevents over 150 disposable bottles annually.' },
  { dayNumber:6,  title:'Line-Dry Your Laundry',           category:'energy', difficulty:'Easy',   estimatedMinutes:10, waterSaved:0,   co2Reduced:1800,plasticAvoided:0,   basePoints:10, description:'Air-dry your laundry today instead of using the dryer. Hang clothes outside or on an indoor rack.',                                                                        ecoFactTip:'Clothes dryers use more electricity than any other household appliance. Line drying one load saves up to 1.8kg of CO₂ and extends your clothes\' life.' },
  { dayNumber:7,  title:'Plant Something Green',            category:'nature', difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:200, plasticAvoided:0,   basePoints:15, description:'Plant a seed, a herb, or a small plant today. Even a single pot of basil on your windowsill counts! Plants purify air and boost mental health.',                          ecoFactTip:'A single tree can absorb up to 22kg of CO₂ per year and produce enough oxygen for 4 people. Starting small still matters.' },
  { dayNumber:8,  title:'Walk or Cycle Instead of Drive',  category:'energy', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:2100,plasticAvoided:0,   basePoints:15, description:'Replace one car trip today with walking or cycling. Even a 2km walk instead of driving prevents significant CO₂ emissions.',                                                 ecoFactTip:'The average car emits about 120g of CO₂ per kilometer. Replacing just one short drive per week saves over 60kg of CO₂ per year.' },
  { dayNumber:9,  title:'Fix a Dripping Tap',              category:'water',  difficulty:'Medium', estimatedMinutes:15, waterSaved:150, co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Check all taps and showers in your home for leaks and fix any drips. A dripping tap can waste thousands of liters per year. Tighten the washer or call a plumber.',      ecoFactTip:'A tap dripping once per second wastes over 11,000 liters of water per year — enough to fill 50 bathtubs.' },
  { dayNumber:10, title:'Switch to Reusable Coffee Cup',   category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:60,  plasticAvoided:22,  basePoints:10, description:'If you buy coffee, bring your own reusable cup. Most cafés offer a discount for this. If you make coffee at home, great — you\'re already ahead!',                       ecoFactTip:'Over 16 billion disposable coffee cups are used annually worldwide. Most are unrecyclable due to their plastic lining.' },
  { dayNumber:11, title:'Eat Seasonal & Local Produce',    category:'nature', difficulty:'Easy',   estimatedMinutes:20, waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:10, description:'Choose fruits and vegetables that are in season locally. Visit a farmer\'s market or check labels for local produce. Seasonal food travels fewer miles to reach you.',    ecoFactTip:'Food transportation accounts for 6% of all food-related emissions. Buying local reduces your food\'s carbon footprint by up to 50%.' },
  { dayNumber:12, title:'Take a Cold Shower',              category:'energy', difficulty:'Hard',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:400, plasticAvoided:0,   basePoints:20, description:'Take a fully cold shower today! Cold showers use zero heating energy. They also improve circulation and boost alertness.',                                                  ecoFactTip:'Heating water accounts for 15–20% of a home\'s total energy use. A cold shower eliminates that entirely and can also improve your immune system.' },
  { dayNumber:13, title:'Start a Compost Bin',             category:'waste',  difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:300, plasticAvoided:0,   basePoints:15, description:'Set up a small compost bin in your kitchen or backyard for food scraps: vegetable peels, coffee grounds, eggshells. Compost returns nutrients to the earth.',             ecoFactTip:'Food waste in landfills produces methane, a greenhouse gas 25x more potent than CO₂. Composting reduces this and creates rich garden fertilizer.' },
  { dayNumber:14, title:'Digital Detox Evening',           category:'energy', difficulty:'Medium', estimatedMinutes:120,waterSaved:0,   co2Reduced:150, plasticAvoided:0,   basePoints:15, description:'Spend the evening without any screens — no phone, TV, or computer. Read a book, take a walk, or play a board game. Reduce phantom energy and mental load.',              ecoFactTip:'The internet produces over 900 million tonnes of CO₂ per year. Reducing screen time for even one evening saves energy at data centers worldwide.' },
  { dayNumber:15, title:'Refuse a Straw',                  category:'waste',  difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:10,  plasticAvoided:5,   basePoints:10, description:'When ordering drinks today, say "no straw please." Alternatively, switch to a reusable metal, bamboo, or silicone straw permanently.',                                     ecoFactTip:'Over 8 billion straws pollute the world\'s beaches. They\'re one of the top 10 items found in ocean cleanups and are eaten by sea turtles and fish.' },
  { dayNumber:16, title:'Buy Second-Hand',                  category:'waste',  difficulty:'Medium', estimatedMinutes:60, waterSaved:0,   co2Reduced:800, plasticAvoided:30,  basePoints:15, description:'Purchase at least one item second-hand today — clothing, books, electronics, or furniture. Check charity shops, thrift stores, or online resale platforms.',               ecoFactTip:'The fashion industry produces 10% of global CO₂ emissions. A single used T-shirt purchase saves 2.5kg of CO₂ versus buying new.' },
  { dayNumber:17, title:'Turn Off Lights When Leaving',    category:'energy', difficulty:'Easy',   estimatedMinutes:1,  waterSaved:0,   co2Reduced:120, plasticAvoided:0,   basePoints:10, description:'Make a conscious habit today: every time you leave a room, switch off the light. Put a sticky note on doors as a reminder if needed.',                                    ecoFactTip:'Lighting accounts for 15% of global electricity consumption. Switching off unused lights consistently reduces a home\'s energy use by up to 10%.' },
  { dayNumber:18, title:'Cook a Zero-Waste Meal',           category:'waste',  difficulty:'Hard',   estimatedMinutes:45, waterSaved:0,   co2Reduced:400, plasticAvoided:50,  basePoints:20, description:'Plan and cook a meal that uses up leftovers, has no packaging waste, and produces no food scraps (or composted ones). Challenge yourself creatively!',                    ecoFactTip:'One-third of all food produced globally — 1.3 billion tonnes — is wasted each year. Zero-waste cooking directly combats this crisis.' },
  { dayNumber:19, title:'Clean Up Your Local Area',         category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:200, basePoints:15, description:'Take a bag outside and pick up litter from your neighborhood, park, or beach for 30 minutes. Every piece of plastic you remove protects local wildlife.',                 ecoFactTip:'8 million metric tonnes of plastic enter our oceans every year. A 30-minute local cleanup can collect up to 5kg of waste before it reaches waterways.' },
  { dayNumber:20, title:'Switch to Eco Search Engine',      category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:50,  plasticAvoided:0,   basePoints:10, description:'Change your default browser to an eco-friendly search engine like Ecosia, which plants trees with its ad revenue. It works just as well as Google!',                     ecoFactTip:'Ecosia has planted over 200 million trees worldwide. Each search you make contributes directly to reforestation in areas most affected by deforestation.' },
  { dayNumber:21, title:'Wash Clothes in Cold Water',       category:'energy', difficulty:'Easy',   estimatedMinutes:5,  waterSaved:0,   co2Reduced:500, plasticAvoided:0,   basePoints:10, description:'Do a laundry load using cold water instead of warm or hot. Modern detergents are formulated to work just as effectively in cold water.',                                   ecoFactTip:'90% of a washing machine\'s energy goes to heating water. Cold washing saves up to 0.5kg of CO₂ per load and preserves your clothes\' colors and fabric.' },
  { dayNumber:22, title:'Eat Vegan for a Full Day',         category:'nature', difficulty:'Hard',   estimatedMinutes:60, waterSaved:4000,co2Reduced:6000,plasticAvoided:0,   basePoints:20, description:'Challenge yourself to eat fully vegan for the entire day. Plan breakfast, lunch, dinner, and snacks in advance. Explore plant-based alternatives.',                      ecoFactTip:'A vegan diet reduces food-related CO₂ emissions by 73% and water use by 55%. One full vegan day saves an average of 4,000 liters of water.' },
  { dayNumber:23, title:'Donate Unused Items',              category:'waste',  difficulty:'Medium', estimatedMinutes:40, waterSaved:0,   co2Reduced:600, plasticAvoided:0,   basePoints:15, description:'Gather clothing, books, or household items you no longer use and arrange to donate them to a charity, shelter, or community center.',                                     ecoFactTip:'Every tonne of donated textiles saves 3.6 tonnes of CO₂ compared to new production. Items in good condition should never go to landfill.' },
  { dayNumber:24, title:'Use Public Transport',             category:'energy', difficulty:'Medium', estimatedMinutes:40, waterSaved:0,   co2Reduced:2500,plasticAvoided:0,   basePoints:15, description:'Use bus, metro, tram, or train for at least one journey today. If you\'re already car-free, great — share this tip with someone who isn\'t.',                            ecoFactTip:'A bus carries up to 50 people using roughly the same fuel as 10 cars. Choosing transit over a solo car trip cuts your per-journey CO₂ by up to 80%.' },
  { dayNumber:25, title:'Reduce Food Packaging',            category:'waste',  difficulty:'Medium', estimatedMinutes:20, waterSaved:0,   co2Reduced:200, plasticAvoided:80,  basePoints:15, description:'Actively choose products with minimal or zero packaging at the grocery store today. Buy loose fruit and veg, use paper bags, and opt for glass over plastic.',           ecoFactTip:'Packaging accounts for over 40% of plastic produced globally. Choosing unwrapped or minimally packaged products directly reduces demand for virgin plastic.' },
  { dayNumber:26, title:'Learn About a Local Eco Issue',    category:'nature', difficulty:'Easy',   estimatedMinutes:20, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:10, description:'Spend 20 minutes researching a local environmental issue — deforestation, river pollution, air quality, or urban heat. Share what you learn with one person.',           ecoFactTip:'Environmental literacy is one of the strongest predictors of pro-environmental behavior. Informed citizens drive policy change and community action.' },
  { dayNumber:27, title:'Install a Low-Flow Shower Head',  category:'water',  difficulty:'Hard',   estimatedMinutes:30, waterSaved:300, co2Reduced:100, plasticAvoided:0,   basePoints:20, description:'Research and purchase a low-flow or water-saving shower head. Installation is typically 10 minutes with a wrench. This is a long-term impact investment.',               ecoFactTip:'Low-flow shower heads use 6–8 liters per minute vs. 15–20L for standard ones. A family of four saves over 160,000 liters of water per year.' },
  { dayNumber:28, title:'Host a Green Conversation',        category:'nature', difficulty:'Medium', estimatedMinutes:30, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'Talk to a friend, colleague, or family member about your 30-day eco challenge. Share what you\'ve learned and inspire them to try even one eco habit.',                ecoFactTip:'Social influence is one of the most powerful drivers of behavior change. Research shows that people are 65% more likely to adopt new habits when others they know have too.' },
  { dayNumber:29, title:'Audit Your Home Energy Use',       category:'energy', difficulty:'Hard',   estimatedMinutes:45, waterSaved:0,   co2Reduced:1000,plasticAvoided:0,   basePoints:20, description:'Conduct a home energy audit: check insulation, draft-proofing, appliance efficiency ratings, and thermostat settings. Identify 3 ways to reduce your energy use long-term.', ecoFactTip:'Home energy audits reduce energy bills by an average of 25%. Proper insulation alone can cut heating costs by 40% and prevent tons of CO₂ annually.' },
  { dayNumber:30, title:'Commit to One Eco Habit Forever',  category:'nature', difficulty:'Medium', estimatedMinutes:10, waterSaved:0,   co2Reduced:0,   plasticAvoided:0,   basePoints:15, description:'You\'ve made it to Day 30! Reflect on your 30-day journey. Choose one eco habit from the challenge that you will commit to permanently. Write it down and share it.', ecoFactTip:'The science of habit formation shows that 30 days of consistent behavior creates a neural pathway that makes the habit automatic. You\'ve already done the hard part!' },
]

const BADGES = [
  { badgeId:'first_leaf',     name:'First Leaf',     icon:'🌱', rarity:'common',    description:'Complete your very first eco task', condition:'Complete Day 1' },
  { badgeId:'green_week',     name:'Green Week',      icon:'🌿', rarity:'uncommon',  description:'Maintain a 7-day streak',          condition:'7-day streak' },
  { badgeId:'halfway_hero',   name:'Halfway Hero',    icon:'⚡', rarity:'rare',      description:'Reach a 15-day streak',            condition:'15-day streak' },
  { badgeId:'eco_warrior',    name:'Eco Warrior',     icon:'🏆', rarity:'legendary', description:'Complete all 30 days',             condition:'Complete 30 days' },
  { badgeId:'water_guardian', name:'Water Guardian',  icon:'💧', rarity:'rare',      description:'Save 100 liters of water',         condition:'100L water saved' },
  { badgeId:'carbon_crusher', name:'Carbon Crusher',  icon:'🌍', rarity:'rare',      description:'Reduce 500g of CO₂',              condition:'500g CO₂ reduced' },
  { badgeId:'waste_buster',   name:'Waste Buster',    icon:'♻️', rarity:'uncommon',  description:'Avoid 200g of plastic',           condition:'200g plastic avoided' },
  { badgeId:'early_bird',     name:'Early Bird',      icon:'🌅', rarity:'uncommon',  description:'Complete a task before 8am',      condition:'Before 8am' },
]

const seed = async () => {
  await connectDB()
  console.log('🌱 Starting seed...')

  // Clear existing
  await Task.deleteMany({})
  await Badge.deleteMany({})
  console.log('  ✓ Cleared existing tasks and badges')

  // Insert tasks
  await Task.insertMany(TASKS)
  console.log(`  ✓ Seeded ${TASKS.length} tasks`)

  // Insert badges
  await Badge.insertMany(BADGES)
  console.log(`  ✓ Seeded ${BADGES.length} badges`)

  console.log('✅ Seed complete!')
  process.exit(0)
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err)
  process.exit(1)
})
